version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 40
    groups:
      major-updates:
        update-types:
          - major
      patch-or-minor:
        update-types:
          - minor
          - patch
