name: "Setup Environment"
description: "Sets up the environment to build the Java project with maven"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: maven

    - name: Extract branch or tag name
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        else
          NORMALIZED_BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
          echo "NORMALIZED_BRANCH_NAME=$NORMALIZED_BRANCH_NAME" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Determine changelist
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          CHANGELIST=''
        else
          CHANGELIST=$(test "${GITHUB_REF#refs/heads/}" == 'master' && echo '' || echo "-$NORMALIZED_BRANCH_NAME-SNAPSHOT")
        fi
        echo "CHANGELIST=$CHANGELIST" >> $GITHUB_ENV
      shell: bash


