CREATE (alice:Human {name: 'Alice'})
CREATE (bob:Human {name: 'Bob'})
CREATE (jane:Human {name: 'Jane'})
CREATE (m1:Movie {name: 'Movie 1'})
CREATE (m2:Movie {name: 'Movie 2'})
CREATE (m3:Movie {name: 'Movie 3'})
CREATE (m4:Movie {name: 'Movie 4'})
CREATE (alice)-[:WATCHED {on: date('2020-01-01')}]->(m1)
CREATE (alice)-[:WATCHED {on: date('2021-01-02')}]->(m2)
CREATE (alice)-[:WATCHED {on: date('2023-01-03')}]->(m1)
CREATE (bob)-[:WATCHED]->(m1)
CREATE (bob)-[:WATCHED {on: date('2001-01-03')}]->(m2)
CREATE (bob)-[:WATCHED {on: date('2001-01-03')}]->(m2)
CREATE (bob)-[:WATCHED {on: date('2023-01-03')}]->(m2)
CREATE (jane)-[:WATCHED]->(m1)
CREATE (jane)-[:WATCHED]->(m2)
CREATE (jane)-[:WATCHED]->(m4)
CREATE (jane)-[:WATCHED]->(m2)
CREATE (jane)-[:WATCHED]->(m1)